### PR TITLE
Fix unit tests to run them on Windows OS

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
@vbauer this is a comment for the Jenkins to run the tests again. Just in case.

**Comment by vbauer** [comment]
Hmm. I didn't get it:
- http://ci.qatools.ru/job/beanloader_pull-request/12/ - this test execution has warnings
- http://ci.qatools.ru/job/beanloader_pull-request/13/ - execution without warnings

Is it normal?

**Comment by innokenty** [comment]
@vbauer not really, but sometimes it happens, because file system events are not hundred percent predictable, as I understand.

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
Okay, that was just a one-time bug, so I gonna merge that. Thank you.

**Comment by vbauer** [comment]
YW

**Pull request merged**
